// Generated by gencpp from file kuka_node/ExecuteTrajectoryResult.msg
// DO NOT EDIT!


#ifndef KUKA_NODE_MESSAGE_EXECUTETRAJECTORYRESULT_H
#define KUKA_NODE_MESSAGE_EXECUTETRAJECTORYRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace kuka_node
{
template <class ContainerAllocator>
struct ExecuteTrajectoryResult_
{
  typedef ExecuteTrajectoryResult_<ContainerAllocator> Type;

  ExecuteTrajectoryResult_()
    : error()  {
    }
  ExecuteTrajectoryResult_(const ContainerAllocator& _alloc)
    : error(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _error_type;
  _error_type error;




  typedef boost::shared_ptr< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteTrajectoryResult_

typedef ::kuka_node::ExecuteTrajectoryResult_<std::allocator<void> > ExecuteTrajectoryResult;

typedef boost::shared_ptr< ::kuka_node::ExecuteTrajectoryResult > ExecuteTrajectoryResultPtr;
typedef boost::shared_ptr< ::kuka_node::ExecuteTrajectoryResult const> ExecuteTrajectoryResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kuka_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kuka_node': ['/home/schwarmcyc/kuka850_ws/src/kuka_node/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'arm_navigation_msgs': ['/opt/ros/indigo/share/arm_navigation_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7285673b1adf9f739dc442f7bdabeac";
  }

  static const char* value(const ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7285673b1adf9f7ULL;
  static const uint64_t static_value2 = 0x39dc442f7bdabeacULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_node/ExecuteTrajectoryResult";
  }

  static const char* value(const ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
std_msgs/Bool error\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
";
  }

  static const char* value(const ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteTrajectoryResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_node::ExecuteTrajectoryResult_<ContainerAllocator>& v)
  {
    s << indent << "error: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_NODE_MESSAGE_EXECUTETRAJECTORYRESULT_H
