// Generated by gencpp from file kuka_node/ExecuteTrajectoryFeedback.msg
// DO NOT EDIT!


#ifndef KUKA_NODE_MESSAGE_EXECUTETRAJECTORYFEEDBACK_H
#define KUKA_NODE_MESSAGE_EXECUTETRAJECTORYFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>

namespace kuka_node
{
template <class ContainerAllocator>
struct ExecuteTrajectoryFeedback_
{
  typedef ExecuteTrajectoryFeedback_<ContainerAllocator> Type;

  ExecuteTrajectoryFeedback_()
    : percentage()  {
    }
  ExecuteTrajectoryFeedback_(const ContainerAllocator& _alloc)
    : percentage(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _percentage_type;
  _percentage_type percentage;




  typedef boost::shared_ptr< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteTrajectoryFeedback_

typedef ::kuka_node::ExecuteTrajectoryFeedback_<std::allocator<void> > ExecuteTrajectoryFeedback;

typedef boost::shared_ptr< ::kuka_node::ExecuteTrajectoryFeedback > ExecuteTrajectoryFeedbackPtr;
typedef boost::shared_ptr< ::kuka_node::ExecuteTrajectoryFeedback const> ExecuteTrajectoryFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kuka_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kuka_node': ['/home/schwarmcyc/kuka850_ws/src/kuka_node/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'arm_navigation_msgs': ['/opt/ros/indigo/share/arm_navigation_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3bc7e4800e0e0e6ec15bd787aad577c";
  }

  static const char* value(const ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3bc7e4800e0e0e6ULL;
  static const uint64_t static_value2 = 0xec15bd787aad577cULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_node/ExecuteTrajectoryFeedback";
  }

  static const char* value(const ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
std_msgs/Float32 percentage\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteTrajectoryFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_node::ExecuteTrajectoryFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_NODE_MESSAGE_EXECUTETRAJECTORYFEEDBACK_H
