// Generated by gencpp from file kuka_node/SetTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef KUKA_NODE_MESSAGE_SETTRAJECTORYRESPONSE_H
#define KUKA_NODE_MESSAGE_SETTRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace kuka_node
{
template <class ContainerAllocator>
struct SetTrajectoryResponse_
{
  typedef SetTrajectoryResponse_<ContainerAllocator> Type;

  SetTrajectoryResponse_()
    : success()  {
    }
  SetTrajectoryResponse_(const ContainerAllocator& _alloc)
    : success(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetTrajectoryResponse_

typedef ::kuka_node::SetTrajectoryResponse_<std::allocator<void> > SetTrajectoryResponse;

typedef boost::shared_ptr< ::kuka_node::SetTrajectoryResponse > SetTrajectoryResponsePtr;
typedef boost::shared_ptr< ::kuka_node::SetTrajectoryResponse const> SetTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kuka_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kuka_node': ['/home/schwarmcyc/kuka850_ws/src/kuka_node/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'arm_navigation_msgs': ['/opt/ros/indigo/share/arm_navigation_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f31cb2e813cfb0e488c574c3b5d9dbe";
  }

  static const char* value(const ::kuka_node::SetTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f31cb2e813cfb0eULL;
  static const uint64_t static_value2 = 0x488c574c3b5d9dbeULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_node/SetTrajectoryResponse";
  }

  static const char* value(const ::kuka_node::SetTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool success\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
";
  }

  static const char* value(const ::kuka_node::SetTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_node::SetTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_node::SetTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_NODE_MESSAGE_SETTRAJECTORYRESPONSE_H
