// Generated by gencpp from file kuka_node/SetTrajectory.msg
// DO NOT EDIT!


#ifndef KUKA_NODE_MESSAGE_SETTRAJECTORY_H
#define KUKA_NODE_MESSAGE_SETTRAJECTORY_H

#include <ros/service_traits.h>


#include <kuka_node/SetTrajectoryRequest.h>
#include <kuka_node/SetTrajectoryResponse.h>


namespace kuka_node
{

struct SetTrajectory
{

typedef SetTrajectoryRequest Request;
typedef SetTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTrajectory
} // namespace kuka_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuka_node::SetTrajectory > {
  static const char* value()
  {
    return "1638531ed93ad03145d87fd812e8e49d";
  }

  static const char* value(const ::kuka_node::SetTrajectory&) { return value(); }
};

template<>
struct DataType< ::kuka_node::SetTrajectory > {
  static const char* value()
  {
    return "kuka_node/SetTrajectory";
  }

  static const char* value(const ::kuka_node::SetTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::kuka_node::SetTrajectoryRequest> should match 
// service_traits::MD5Sum< ::kuka_node::SetTrajectory > 
template<>
struct MD5Sum< ::kuka_node::SetTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_node::SetTrajectory >::value();
  }
  static const char* value(const ::kuka_node::SetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_node::SetTrajectoryRequest> should match 
// service_traits::DataType< ::kuka_node::SetTrajectory > 
template<>
struct DataType< ::kuka_node::SetTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::kuka_node::SetTrajectory >::value();
  }
  static const char* value(const ::kuka_node::SetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuka_node::SetTrajectoryResponse> should match 
// service_traits::MD5Sum< ::kuka_node::SetTrajectory > 
template<>
struct MD5Sum< ::kuka_node::SetTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_node::SetTrajectory >::value();
  }
  static const char* value(const ::kuka_node::SetTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_node::SetTrajectoryResponse> should match 
// service_traits::DataType< ::kuka_node::SetTrajectory > 
template<>
struct DataType< ::kuka_node::SetTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::kuka_node::SetTrajectory >::value();
  }
  static const char* value(const ::kuka_node::SetTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUKA_NODE_MESSAGE_SETTRAJECTORY_H
