(cl:defpackage kuka_node-msg
  (:use )
  (:export
   "<EXECUTETRAJECTORYFEEDBACK>"
   "EXECUTETRAJECTORYFEEDBACK"
   "<EXECUTETRAJECTORYACTIONRESULT>"
   "EXECUTETRAJECTORYACTIONRESULT"
   "<EXECUTETRAJECTORYGOAL>"
   "EXECUTETRAJECTORYGOAL"
   "<EXECUTETRAJECTORYRESULT>"
   "EXECUTETRAJECTORYRESULT"
   "<EXECUTETRAJECTORYACTIONGOAL>"
   "EXECUTETRAJECTORYACTIONGOAL"
   "<EXECUTETRAJECTORYACTION>"
   "EXECUTETRAJECTORYACTION"
   "<EXECUTETRAJECTORYACTIONFEEDBACK>"
   "EXECUTETRAJECTORYACTIONFEEDBACK"
  ))

