; Auto-generated. Do not edit!


(cl:in-package kuka_node-msg)


;//! \htmlinclude ExecuteTrajectoryResult.msg.html

(cl:defclass <ExecuteTrajectoryResult> (roslisp-msg-protocol:ros-message)
  ((error
    :reader error
    :initarg :error
    :type std_msgs-msg:Bool
    :initform (cl:make-instance 'std_msgs-msg:Bool)))
)

(cl:defclass ExecuteTrajectoryResult (<ExecuteTrajectoryResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecuteTrajectoryResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecuteTrajectoryResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kuka_node-msg:<ExecuteTrajectoryResult> is deprecated: use kuka_node-msg:ExecuteTrajectoryResult instead.")))

(cl:ensure-generic-function 'error-val :lambda-list '(m))
(cl:defmethod error-val ((m <ExecuteTrajectoryResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kuka_node-msg:error-val is deprecated.  Use kuka_node-msg:error instead.")
  (error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecuteTrajectoryResult>) ostream)
  "Serializes a message object of type '<ExecuteTrajectoryResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'error) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecuteTrajectoryResult>) istream)
  "Deserializes a message object of type '<ExecuteTrajectoryResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'error) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecuteTrajectoryResult>)))
  "Returns string type for a message object of type '<ExecuteTrajectoryResult>"
  "kuka_node/ExecuteTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecuteTrajectoryResult)))
  "Returns string type for a message object of type 'ExecuteTrajectoryResult"
  "kuka_node/ExecuteTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecuteTrajectoryResult>)))
  "Returns md5sum for a message object of type '<ExecuteTrajectoryResult>"
  "d7285673b1adf9f739dc442f7bdabeac")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecuteTrajectoryResult)))
  "Returns md5sum for a message object of type 'ExecuteTrajectoryResult"
  "d7285673b1adf9f739dc442f7bdabeac")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecuteTrajectoryResult>)))
  "Returns full string definition for message of type '<ExecuteTrajectoryResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Bool error~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecuteTrajectoryResult)))
  "Returns full string definition for message of type 'ExecuteTrajectoryResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Bool error~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecuteTrajectoryResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'error))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecuteTrajectoryResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecuteTrajectoryResult
    (cl:cons ':error (error msg))
))
